services:
    mqtt5:
        image: eclipse-mosquitto
        container_name: mqtt5
        restart: always
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./conf:/mosquitto/config:rw
            - ./data:/mosquitto/data:rw
            - ./log:/mosquitto/log:rw
volumes:
    conf:
    data:
    log: